### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by krainboltgreene** [VikParuchuri/marker#1]
```
Traceback (most recent call last):
  File "marker/convert_single.py", line 22, in <module>
    full_text, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, parallel_factor=args.parallel_factor)
  File "marker/marker/convert.py", line 120, in convert_single_pdf
    blocks = order_blocks(
  File "marker/marker/ordering.py", line 103, in order_blocks
    add_column_counts(doc, doc_blocks, model, batch_size)
  File "marker/marker/ordering.py", line 97, in add_column_counts
    predictions = batch_inference(rgb_images, bboxes, words, model)
  File "marker/marker/ordering.py", line 58, in batch_inference
    encoding = processor(
  File "/home/vscode/.cache/pypoetry/virtualenvs/marker-rdHpm9Sx-py3.10/lib/python3.10/site-packages/transformers/models/layoutlmv3/processing_layoutlmv3.py", line 114, in __call__
    features = self.image_processor(images=images, return_tensors=return_tensors)
  File "/home/vscode/.cache/pypoetry/virtualenvs/marker-rdHpm9Sx-py3.10/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 546, in __call__
    return self.preprocess(images, **kwargs)
  File "/home/vscode/.cache/pypoetry/virtualenvs/marker-rdHpm9Sx-py3.10/lib/python3.10/site-packages/transformers/models/layoutlmv3/image_processing_layoutlmv3.py", line 299, in preprocess
    images = make_list_of_images(images)
  File "/home/vscode/.cache/pypoetry/virtualenvs/marker-rdHpm9Sx-py3.10/lib/python3.10/site-packages/transformers/image_utils.py", line 124, in make_list_of_images
    if is_batched(images):
  File "/home/vscode/.cache/pypoetry/virtualenvs/marker-rdHpm9Sx-py3.10/lib/python3.10/site-packages/transformers/image_utils.py", line 97, in is_batched
    return is_valid_image(img[0])
IndexError: list index out of range
```

I can get as much information as you need.

**Comment by VikParuchuri** [comment]
Try the latest master, it should be fixed.  I think it was related to the `--max` flag.

**Comment by krainboltgreene** [comment]
That fixed it, thanks!
