### ISSUE TITLE
RuntimeError: unable to open shared memory objec  Too many open files (24)

### ISSUE THREAD

**Issue by wwjCMP** [VikParuchuri/marker#181]
Traceback (most recent call last):
  File "/home/try/.local/bin/marker", line 8, in <module>
  File "/home/try/.local/lib/python3.11/site-packages/convert.py", line 118, in main
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2503, in share_memory
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
  [Previous line repeated 4 more times]
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
  File "/home/try/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2503, in <lambda>
  File "/home/try/.local/lib/python3.11/site-packages/torch/_tensor.py", line 711, in share_memory_
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 905, in _share_memory_
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 304, in wrapper
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 370, in share_memory_
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 256, in share_memory_
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 304, in wrapper
  File "/home/try/.local/lib/python3.11/site-packages/torch/storage.py", line 374, in _share_fd_cpu_
RuntimeError: unable to open shared memory object </torch_386477_2317880123_2043> in read-write mode: Too many open files (24)
Traceback (most recent call last):
  File "/opt/software/anaconda3/lib/python3.11/weakref.py", line 666, in _exitfunc
    f()
  File "/opt/software/anaconda3/lib/python3.11/weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/software/anaconda3/lib/python3.11/tempfile.py", line 894, in _cleanup
    cls._rmtree(name, ignore_errors=ignore_errors)
  File "/opt/software/anaconda3/lib/python3.11/tempfile.py", line 890, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/opt/software/anaconda3/lib/python3.11/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/opt/software/anaconda3/lib/python3.11/shutil.py", line 635, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/opt/software/anaconda3/lib/python3.11/shutil.py", line 631, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
         ^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '/tmp/tmpypm2v9o9'

**Comment by joeamroo** [comment]
Run this to temporarily increase how many files you can open at once: ulimit -n 4096

**Comment by wwjCMP** [comment]
> Run this to temporarily increase how many files you can open at once: ulimit -n 4096

you are right, thanks
