### ISSUE TITLE
I get this error : Number of processes must be at least 1 for multi gplu convertion 

### ISSUE THREAD

**Issue by issa2k23** [VikParuchuri/marker#185]
I am using windows 10 and this is the command : marker in-pdf out-pdf --num_chunks 2 --chunk_idx 2 --workers 15

Converting 0 pdfs in chunk 3/2 with 0 processes, and storing in F:\PDF-Marker\out-pdf
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AI\anaconda3\envs\Marker\Scripts\marker.exe\__main__.py", line 7, in <module>
  File "D:\AI\anaconda3\envs\Marker\Lib\site-packages\convert.py", line 123, in main
    with mp.Pool(processes=total_processes, initializer=worker_init, initargs=(model_lst,)) as pool:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\anaconda3\envs\Marker\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\anaconda3\envs\Marker\Lib\multiprocessing\pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by joeamroo** [comment]
Are the files in a subdirectory inside of "in-pdf"?  It needs to be in that main directory you specify.

**Comment by issa2k23** [comment]
yes they are, when I run the single file conversion just works. but I have this problem when I want to run for multi files (in a directory) and multi-gpu
