### ISSUE TITLE
DLL Import error images

### ISSUE THREAD

**Issue by Oddivh** [VikParuchuri/marker#227]
Anyone any idea what causes this error? (Running on Windows 11, with Nvidia GPU/cuda 12.5, conda environment.

> \AppData\Local\miniconda3\Lib\site-packages\PIL\Image.py", line 88, in <module>
>     from . import _imaging as core
> 
> ImportError: DLL load failed while importing _imaging: The specified module could not be found.

**Comment by Oddivh** [comment]
More info about the error message:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...\AppData\Local\miniconda3\Scripts\marker_single.exe\__main__.py", line 4, in <module>
  File "...\AppData\Local\miniconda3\Lib\site-packages\convert_single.py", line 6, in <module>
    from marker.convert import convert_single_pdf
  File "...\AppData\Local\miniconda3\Lib\site-packages\marker\convert.py", line 9, in <module>
    from PIL import Image

**Comment by VikParuchuri** [comment]
This is related to PIL (Pillow), not to marker.  I'd look into that library support
