### ISSUE TITLE
ImportError: Cannot import 'flush_cuda_memory' from marker.utils

### ISSUE THREAD

**Issue by Willseed** [VikParuchuri/marker#241]
# ImportError: Cannot import 'flush_cuda_memory' from marker.utils

## Description
I'm encountering an `ImportError` when trying to run the `marker_single` script. The error suggests that the `flush_cuda_memory` function cannot be imported from the `marker.utils` module.

## Error Message
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jgh98\AppData\Local\pypoetry\Cache\virtualenvs\pdf-tool-wBScWOp2-py3.12\Scripts\marker_single.exe\__main__.py", line 4, in <module>
  File "C:\Users\jgh98\AppData\Local\pypoetry\Cache\virtualenvs\pdf-tool-wBScWOp2-py3.12\Lib\site-packages\convert_single.py", line 8, in <module>
    from marker.convert import convert_single_pdf
  File "C:\Users\jgh98\AppData\Local\pypoetry\Cache\virtualenvs\pdf-tool-wBScWOp2-py3.12\Lib\site-packages\marker\convert.py", line 11, in <module>
    from marker.utils import flush_cuda_memory
ImportError: cannot import name 'flush_cuda_memory' from 'marker.utils' (C:\Users\jgh98\AppData\Local\pypoetry\Cache\virtualenvs\pdf-tool-wBScWOp2-py3.12\Lib\site-packages\marker\utils\__init__.py)
```

## Environment
- OS: Windows
- Python version: 3.12
- Package manager: Poetry

## Steps to Reproduce
1. Set up the project using Poetry
2. Attempt to run the `marker_single` script

## Expected Behavior
The script should run without import errors.

## Actual Behavior
An `ImportError` is raised, indicating that `flush_cuda_memory` cannot be imported from `marker.utils`.

## Additional Context
This error occurs in a Poetry-managed virtual environment. It seems that the `flush_cuda_memory` function is either missing from the `marker.utils` module or not properly exported.

## Possible Solutions
1. Check if the `flush_cuda_memory` function is defined in the `marker.utils` module.
2. Ensure that the function is properly exported in the `__init__.py` file of the `marker.utils` package.
3. Verify that all dependencies are correctly installed and up-to-date.

Any assistance or insights into resolving this issue would be greatly appreciated. Thank you in advance for your help!

**Comment by sagaruprety** [comment]
I had this same error, then I realised that I also had 'marker' library installed. Mistakenly I had installed 'marker' instead of 'marker-pdf' via pip. Perhaps it is an earlier version of marker-pdf. When I uninstalled 'marker', I no longer had this error.
