### ISSUE TITLE
ImportError: cannot import name 'segformer' from 'surya.model.detection' (unknown location)

### ISSUE THREAD

**Issue by Beaverfffan** [VikParuchuri/marker#247]
marker /mnt/f/markerpdfsource /mnt/f/output/folder --workers 1 --max 1000 --langs Chinese
Traceback (most recent call last):
  File "/home/shenteng/anaconda3/bin/marker", line 5, in <module>
    from convert import main
  File "/home/shenteng/anaconda3/lib/python3.12/site-packages/convert.py", line 9, in <module>
    from marker.convert import convert_single_pdf
  File "/home/shenteng/anaconda3/lib/python3.12/site-packages/marker/convert.py", line 14, in <module>
    from marker.ocr.recognition import run_ocr
  File "/home/shenteng/anaconda3/lib/python3.12/site-packages/marker/ocr/recognition.py", line 10, in <module>
    from marker.models import setup_recognition_model
  File "/home/shenteng/anaconda3/lib/python3.12/site-packages/marker/models.py", line 2, in <module>
    from surya.model.detection import segformer
ImportError: cannot import name 'segformer' from 'surya.model.detection' (unknown location)

**Comment by Blackskyliner** [comment]
You need to pin the ocr lib to surya-ocr = "^0.4.14"` until code is adjusted for new interfaces.
