### ISSUE TITLE
Improving OCR through higher image DPI?

### ISSUE THREAD

**Issue by kkarski** [VikParuchuri/marker#262]
I am trying to improve OCR, especially for tables, by increasing the DPI of the images captured by markers. I am using the following command and paramter settings but am getting an error every time:

` SURYA_DETECTOR_DPI=120 SURYA_OCR_DPI=120 SURYA_LAYOUT_DPI=120 marker ./reports ./reports`

Are there some additional settings I am missing which I also need to update?

Error:

```
Detecting bboxes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:04<00:00,  2.27it/s]
Detecting bboxes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:06<00:00,  2.81it/s]
Recognizing Text: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 34/34 [00:31<00:00,  1.09it/s]
Detecting bboxes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:05<00:00,  1.45it/s]
Recognizing Text:  65%|███████████████████████████████████████████████████████████████████████▏                                     | 49/75 [00:37<00:12,  2.13it/s]../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [486,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [486,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [486,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [486,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
...
../aten/src/ATen/native/cuda/Indexing.cu:1284: indexSelectLargeIndex: block: [188,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Finding reading order:   0%|                                                                                                                  | 0/4 [00:00<?, ?it/s]
Error converting /home/kkarski/dev/gits/accountantai/reports/companies_house_document.pdf: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/convert.py", line 59, in process_single_pdf
    full_text, images, out_metadata = convert_single_pdf(filepath, model_refs, metadata=metadata)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/marker/convert.py", line 117, in convert_single_pdf
    surya_order(doc, pages, order_model, batch_multiplier=batch_multiplier)
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/marker/layout/order.py", line 33, in surya_order
    order_results = batch_ordering(images, bboxes, order_model, processor, batch_size=int(get_batch_size() * batch_multiplier))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/surya/ordering.py", line 68, in batch_ordering
    return_dict = model(
                  ^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/surya/model/ordering/encoderdecoder.py", line 61, in forward
    decoder_outputs = self.decoder(
                      ^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/surya/model/ordering/decoder.py", line 527, in forward
    outputs = self.model.decoder(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/surya/model/ordering/decoder.py", line 342, in forward
    inputs_embeds = self.embed_tokens(input_boxes, input_boxes_counts, past_key_values_length) * self.embed_scale
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kkarski/.accountantai/lib/python3.11/site-packages/surya/model/ordering/decoder.py", line 270, in forward
    embedded[j, box_start:box_end] = embedded[j, box_start:box_end] + self.box_pos_embed.weight[:box_count]
                                     ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by VikParuchuri** [comment]
The detector is very dpi sensitive, so I wouldn't increase it.  OCR now uses higher dpi by default
