### ISSUE TITLE
MPS backend out of memory Issue

### ISSUE THREAD

**Issue by HeMuling** [VikParuchuri/marker#321]
I ran single ocr on M1 chip with 16GB of ram, set `--batch_multiplier` to 2, `--max_pages` to 14,  and I encountered this:

```
Loaded detection model vikp/surya_det3 on device mps with dtype torch.float16
Loaded detection model vikp/surya_layout3 on device mps with dtype torch.float16
Loaded reading order model vikp/surya_order on device mps with dtype torch.float16
Loaded recognition model vikp/surya_rec2 on device mps with dtype torch.float16
Loaded texify model to mps with torch.float16 dtype
Loaded recognition model vikp/surya_tablerec on device mps with dtype torch.float16
Detecting bboxes: 100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.62s/it]
Recognizing Text:  40%|███████████████████████████████████▏                                                    | 2/5 [00:40<01:01, 20.35s/it]
Traceback (most recent call last):
  File "/Users/he_muling/miniconda3/envs/ocr/bin/marker_single", line 8, in <module>
    sys.exit(main())
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/convert_single.py", line 33, in main
    full_text, images, out_meta = convert_single_pdf(fname, model_lst, max_pages=args.max_pages, langs=langs, batch_multiplier=args.batch_multiplier, start_page=args.start_page)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/marker/convert.py", line 98, in convert_single_pdf
    pages, ocr_stats = run_ocr(doc, pages, langs, ocr_model, batch_multiplier=batch_multiplier, ocr_all_pages=ocr_all_pages)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/marker/ocr/recognition.py", line 53, in run_ocr
    new_pages = surya_recognition(doc, ocr_idxs, langs, rec_model, pages, batch_multiplier=batch_multiplier)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/marker/ocr/recognition.py", line 95, in surya_recognition
    results = run_recognition(images, surya_langs, rec_model, processor, polygons=polygons, batch_size=int(get_batch_size() * batch_multiplier))
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/ocr.py", line 31, in run_recognition
    rec_predictions, _ = batch_recognition(all_slices, all_langs, rec_model, rec_processor, batch_size=batch_size)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/recognition.py", line 94, in batch_recognition
    encoder_hidden_states_batch = model.encoder(pixel_values=encoder_pixel_values).last_hidden_state
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 852, in forward
    encoder_outputs = self.encoder(
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 722, in forward
    layer_outputs = layer_module(
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 640, in forward
    layer_outputs = layer_module(
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 569, in forward
    attention_outputs = self.attention(
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 439, in forward
    self_outputs = self.self(hidden_states, attention_mask, head_mask, output_attentions)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/he_muling/miniconda3/envs/ocr/lib/python3.10/site-packages/surya/model/recognition/encoder.py", line 377, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: MPS backend out of memory (MPS allocated: 7.17 GB, other allocations: 10.81 GB, max allowed: 18.13 GB). Tried to allocate 462.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
```

is there a bug here, or is 16GB of ram not enough for such a task?

**Comment by ChambersXDU** [comment]
The same issue on a M1 pro Mac.

**Comment by daronstinnett** [comment]
Same on a M3 16GB, regardless of number of pages attempted.

**Comment by vanAmsterdam** [comment]
same on M3 macbook pro 18gb, 16 pages book chapter

**Comment by bellicose100xp** [comment]
Same issue M3 MacBook 16 GB

**Comment by moshetanzer** [comment]
Same issue on M1 - with a message from python about a memory leak?

**Comment by rglamazda** [comment]
Same m1 pro 16gb

**Comment by RamiroLC13** [comment]
Same here, m2 16gb RAM
