### ISSUE TITLE
got an error when using convert_single.py to convert pdf to md

### ISSUE THREAD

**Issue by ZeyuTeng96** [VikParuchuri/marker#46]
running commands: python convert_single.py ./test.pdf ./test.md

Error:

Traceback (most recent call last):
  File "/marker/convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "/marker/marker/convert.py", line 9, in <module>
    from marker.postprocessors.editor import edit_full_text
  File "/marker/marker/postprocessors/editor.py", line 11, in <module>
    tokenizer = AutoTokenizer.from_pretrained(settings.EDITOR_MODEL_NAME)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 736, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2073, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<pad>' found. Should have index 259 but has index 0 in saved vocabulary.

**Comment by VikParuchuri** [comment]
Does it work if you disable the editor model? `ENABLE_EDITOR_MODEL=false` - it should be disabled by default, so you can just remove where you enable it.

**Comment by iamlemec** [comment]
The problem is that line 11 of editor.py is at the top level of the module, so will get executed on import even when `ENABLE_EDITOR_MODEL` is `False`. Just commenting that line our worked for me.

**Comment by VikParuchuri** [comment]
Thanks for the fix.  I don't know why this issue is coming up now, but that tokenizer is actually not used, so I'll remove it and merge the fix to master.
