### ISSUE TITLE
How do I run Marker (convert_single.py, and others) Offline?

### ISSUE THREAD

**Issue by goapurva** [VikParuchuri/marker#48]
Hello, 

I am trying out Marker in an environment that's not connected to the internet (security reasons). I am running into several issues even running convert_single.py.

(it's a Windows 10 virtual env).

Can you help me with how to run Marker offline?

Thank you,
Apurva

Errors for reference:
(marker-py3.10) (marker) C:\Users\APATHAK2\Documents\marker-master\marker-master>**python convert_single.py C:\Users\APATHAK2\Documents\marker-master\marker-master\6941.pdf C:\Users\APATHAK2\Documents\marker-master\marker-master\6941.md --parallel_factor 2 --max_pages 22**
Traceback (most recent call last):
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\APATHAK2\AppData\Local\pypoetry\Cache\virtualenvs\marker-UNt7FmZX-py3.10\lib\site-packages\urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "C:\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()

**Comment by VikParuchuri** [comment]
This looks like it is due to huggingface transformers trying to download/update the models.  You could check `settings.py` for the various model names, download them to disk, and then replace the model names in the settings with the folders you downloaded them to.
