### ISSUE TITLE
Not compatible with python 3.9?

### ISSUE THREAD

**Issue by milep-osgenic** [VikParuchuri/marker#7]
I was able to install the project with pyenv and 3.9.18 on macos, but when running convert_single.py I got an error:
```
Traceback (most recent call last):
  File "/Users/milep/projects/marker/convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "/Users/milep/projects/marker/marker/convert.py", line 3, in <module>
    from marker.cleaners.table import merge_table_blocks, create_new_tables
  File "/Users/milep/projects/marker/marker/cleaners/table.py", line 2, in <module>
    from marker.schema import Line, Span, Block, Page
  File "/Users/milep/projects/marker/marker/schema.py", line 56, in <module>
    class Span(BboxElement):
  File "/Users/milep/projects/marker/marker/schema.py", line 61, in Span
    ascender: float | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

It worked with the 3.10.13 version.

**Comment by VikParuchuri** [comment]
Thanks for reporting, will look into this.

**Comment by emcmanus** [comment]
Quick steps to get started with 3.10 on macos

```
brew install python@3.10
python3.10 -m pip install poetry
python3.10 -m poetry install
python3.10 -m poetry shell

# ready to use
python3.10 convert_single.py .... # Or convert.py
```

**Comment by samuell** [comment]
Indeed. There are other Python 3.9 incompatibilities, such as the use of the match/case syntax, which reportedly is available only since 3.10:

```python
Traceback (most recent call last):
  File "/home/samuel/opt/marker/convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "/home/samuel/opt/marker/marker/convert.py", line 4, in <module>
    from marker.extract_text import get_text_blocks
  File "/home/samuel/opt/marker/marker/extract_text.py", line 6, in <module>
    from marker.ocr.page import ocr_entire_page
  File "/home/samuel/opt/marker/marker/ocr/page.py", line 16
    match settings.OCR_ENGINE:
          ^
SyntaxError: invalid syntax
```

```python
Traceback (most recent call last):
  File "/home/samuel/opt/marker/convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "/home/samuel/opt/marker/marker/convert.py", line 12, in <module>
    from marker.markdown import merge_spans, merge_lines, get_full_text
  File "/home/samuel/opt/marker/marker/markdown.py", line 68
    match block_type:
          ^
SyntaxError: invalid syntax
```

**Comment by timothyasp** [comment]
Also getting this with 3.9 - but when trying with 3.10 getting pydantic errors.

`ImportError: cannot import name 'field_validator' from 'pydantic' (/usr/local/lib/python3.10/site-packages/pydantic/__init__.cpython-310-darwin.so)`

**Comment by timothyasp** [comment]
Looks like there's some more 3.9 bugs from the most recent commit - 


```
Traceback (most recent call last):
  File "/Users/tasp/Code/projects/marker/convert_single.py", line 3, in <module>
    from marker.convert import convert_single_pdf
  File "/Users/tasp/Code/projects/marker/marker/convert.py", line 4, in <module>
    from marker.extract_text import get_text_blocks
  File "/Users/tasp/Code/projects/marker/marker/extract_text.py", line 6, in <module>
    from marker.ocr.page import ocr_entire_page
  File "/Users/tasp/Code/projects/marker/marker/ocr/page.py", line 16
    match settings.OCR_ENGINE:
          ^
SyntaxError: invalid syntax
```
